# Generated by Django 2.2 on 2019-09-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, null=True)),
                ('clash', models.TextField(blank=True, null=True)),
                ('rc', models.TextField(blank=True, null=True)),
                ('enigma', models.TextField(blank=True, null=True)),
                ('cday', models.TextField(blank=True, null=True)),
                ('rday', models.TextField(blank=True, null=True)),
                ('eday', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('events', models.TextField(blank=True, null=True)),
                ('field_id', models.TextField(blank=True, null=True)),
                ('name1', models.TextField(blank=True, null=True)),
                ('name2', models.TextField(blank=True, null=True)),
                ('name3', models.TextField(blank=True, null=True)),
                ('name4', models.TextField(blank=True, null=True)),
                ('phone1', models.TextField(blank=True, null=True)),
                ('phone2', models.TextField(blank=True, null=True)),
                ('receipt_no', models.TextField(blank=True, null=True)),
                ('total', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('session', models.TextField(default='true')),
            ],
        ),
        migrations.CreateModel(
            name='SlotsTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
