# Generated by Django 2.2 on 2019-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cday',
            new_name='c_day',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='eday',
            new_name='e_day',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='rday',
            new_name='email_response',
        ),
        migrations.AddField(
            model_name='booking',
            name='r_day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
