# Generated by Django 2.2 on 2019-09-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20190918_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
